### ISSUE TITLE
Support import from computer to watch

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ColinPitrat/kalenji-gps-watch-reader#40]
```
Some watches such as onMove 510 have a navigation function. GPX tracks can be 
imported and then followed during a training session. It would be interesting 
to add that functionnality to your tool.


```

Original issue reported on code.google.com by `col.patr...@gmail.com` on 15 Sep 2014 at 6:57

**Comment by ColinPitrat** [comment]
*Copy paste from google (issue updated while migrating to github):*

Hello Colin,

* issue during guiding *

After uploading the data, but before guiding, everything seems fine. The preview is oke. When I choose guiding, it still is. I see the route that I'am suppose to walk.

But when I actually press 'start guiding' an additional line appears. It's from the point where I am standing at to the side of the screen. I can zoom in or out, that doesn't matter. The line stays there. It seems to be directed to the most 

remote point of the route, but that's not always the case. Sometimes the line crosses the route at the most remote point and sometimes I see 2 parallel lines.

I've done the same test with the official software. Everything was oke then. No problems. No additional lines. I also did the same test with your kalenji-reader and a Kalenjij 700. Than also everything was oke. 

I hope that you can make something out of this.

Regards,
Nicolas



Hello Colin,

During uploading I encoutered the following issues:

* truncating session *
Files containing a lot of points are compressed to 200 points using ReducePoints. But sometimes still an error appears: 'too much points to export - truncating session'. Example: truncation_error.gpx

* too much compression *
Files containing a lot of points should be compressed to 200 point using ReducePoints. But sometimes compression is much heavier. For instance reducing session from 250 tot 183 points. Example: compresses250to183.gpx

* using gpsbabel *
I tried to solve these two issues using gpsbabel and simplify the gpx-input-files to 200 points before calling kalenji-reader. That was not good enough. With simplify set on 199 points the problems were solved.

* filename *
I noticed that kalenji-reader displays session-name (information out of metadata) as name of the route. The official software uses the filename (the part before .gpx). This is not an issue. I prefer the method of the kalenji-reader. But I just wanted to mention it. Perhaps there's a relation with some other issues.

* easing end-user experience * 
I wrote a little script that calls the kalenji-reader. I place all the files that have to be uploaded in a directory. The script processes all the files one-by-one (i.e. removes white-spaces out of names, reduces # points to 199) and uploads them to the watch. I don't have to bother about spelling the names correctly or so. It just uploads all files in the directory. I found that to be very easy.

Regards
Nicolas

**Comment by ColinPitrat** [comment]
Concerning your last updates:
 - I'll try to understand why you have this straight line, it looks like the start point of the session is in the middle of the track, not near where you are !
 - The other problems you have comes from ReducePoint filter not being very nice: it iteratively reduce the min angle to consider until reaching a number of points below 200. Sometimes it ends up being way below 200, but it could add some points to be just at the limit (199 or 200, to be verified)
 - If I understand well, spaces should be removed from name because they are not properly handled by the device ? If both this and the ReducePoint filter were fixed, you script would only consist in looping on the files to import them.

**Comment by Eindhoven562** [comment]
Hello Colin,

I don't know why I have this straight line. It's there right from the start. I can use guiding anyway (from start to finish), but all that time the line is present. It always starts at the point where I am standing at that moment. I don't think that it's going to the middle of the track. It's more like going to the most far end of the track (as the crow flies). Please let me know what I can do you help you further on this issue.

Your last remark is correct. The script is only used do handle multiple files in an easy way.

**Comment by Eindhoven562** [comment]
Hello Colin,

I hope to help you out with the following information.

I have uploaded the file OnmoveTEST.gpx to the watch using both the official Geonaute-uploader and the Kalenji-gps-watchreader. The watch produced *.GHR-files. I will upload them here. I hope that you can analyze them and find the differences between them so that you can improve the program.

First uploaded with the official Geonaute-uploader. 
Preview displays says OnmoveTEST 8.98 km.
Detailscreen displays 8.98 km. 385 m up. 386 m down.
Guiding is oke. No additional lines on the screen.
File in watch: F3SB2907.GHR

After that uploaded with the Kalenji-gps-watchreader
Preview displays says Irrel 8.88 km.
Detailscreen displays 8.88 km. 752 m up. 743 m down.
Guiding is not oke. Additional lines on the screen.
File in watch: E9HG0000.GHR.

Regards,
Nicolas

**Comment by Eindhoven562** [comment]
Hello Colin,

I hope to help you out with the following information.

I have uploaded the file OnmoveTEST.gpx to the watch using both the official Geonaute-uploader and the Kalenji-gps-watchreader. The watch produced *.GHR-files. I will upload them here. I hope that you can analyze them and find 

the differences between them so that you can improve the program.

First uploaded with the official Geonaute-uploader. 
Preview displays says OnmoveTEST 8.98 km.
Detailscreen displays 8.98 km. 385 m up. 386 m down.
Guiding is oke. No additional lines on the screen.
File in watch: F3SB2907.GHR

After that uploaded with the Kalenji-gps-watchreader
Preview displays says Irrel 8.88 km.
Detailscreen displays 8.88 km. 752 m up. 743 m down.
Guiding is not oke. Additional lines on the screen.
File in watch: E9HG0000.GHR.

Regards,
Nicolas

**Comment by Eindhoven562** [comment]
Hello Colin,

I hope to help you out with the following information.

I have uploaded the file OnmoveTEST.gpx to the watch using both the official Geonaute-uploader and the Kalenji-gps-watchreader. The watch produced *.GHR-files. I will upload them here. I hope that you can analyze them and find the differences between them so that you can improve the program.

First uploaded with the official Geonaute-uploader. 
Preview displays says OnmoveTEST 8.98 km.
Detailscreen displays 8.98 km. 385 m up. 386 m down.
Guiding is oke. No additional lines on the screen.
File in watch: F3SB2907.GHR

After that uploaded with the Kalenji-gps-watchreader
Preview displays says Irrel 8.88 km.
Detailscreen displays 8.88 km. 752 m up. 743 m down.
Guiding is not oke. Additional lines on the screen.
File in watch: E9HG0000.GHR.

Remark: Gibhub only supports a limited number of file types. 
*.gpx or *.ghr are not accepted. I therefore had to rename the files:

OnmoveTEST.gpx --> OnmoveTEST.jpg
F3SB2907.GHR --> F3SB2907.jpg
E9HG0000.GHR --> E9HG0000.jpg

Regards,
Nicolas

![e9hg0000](https://cloud.githubusercontent.com/assets/11527891/6880989/767a862c-d54b-11e4-8571-71af0654d88f.jpg)
![f3sb2907](https://cloud.githubusercontent.com/assets/11527891/6880991/767f18ea-d54b-11e4-9397-8bf9d40313e5.jpg)
![onmovetest](https://cloud.githubusercontent.com/assets/11527891/6880990/767cdb8e-d54b-11e4-8db3-c1ece07aaf7b.jpg)

**Comment by Eindhoven562** [comment]
Hello Colin,

I did some further testing.

As mentioned before, guiding is not oke when the route consists out off approximately 200 points (additional line appears). But when the number of points is significantly reduced (for example to 100 points) then guiding seems to be oke (no additional line). I don't know exactly what the limit is, but a quick test shows that 150 points is still too much (guiding is not oke then).

I hope that this information helps you further.

Regards,
Nicolas

**Comment by Eindhoven562** [comment]
Hello Colin,

Some time ago I posted GHR-files produced with the official Geonaute-uploader (guiding was correct) and with the Kalenji-gps-watchreader (guiding with errors). Have you been able to compare them with each other to find out what causes the errors? 

Is there anything I can do to help you?

Regards,
Nicolas

**Comment by Eindhoven562** [comment]
Hello Colin,

I still have problems with guiding. 

If I use the official Geonaute-uploader everything is working fine. When using the Kalenji-gps-watchreader additional lines appear on the screen. This issue seems to occure only with a large number of points (say more than 100). 

In my post dated March 28 I submitted the *GHR files produced with both uploaders. Can you please compare them to see what is causing the problem? A fix would be great!

If you need any additional information or testing, please let me know.

Regard,
Nicolas

**Comment by ColinPitrat** [comment]
Hello,

having a look at the files, the one produced by kalenji_reader contains 199 points which corresponds to the content of the GPX. All the points in the file produced by Geonaute-uploader can be found in the file produced by kalenji_reader, but there are additional points in the one of kalenji_reader. The additional points in the output of kalenji_reader are really intermediate points (the latitude / longitude are progressing from the previous point to the next point).

It seems Geonaute-uploader drastically reduce the number of points.

The only issue I could find is that the padding at the end of the file wasn't properly done by kalenji_reader. I fixed it, can you give it another try with a fresh build from git repo ? Or do you need me to redeliver one ?

Regards,
Colin

**Comment by Eindhoven562** [comment]
Hello Colin,

I don't understand what you mean by 'build it from git repo'. I need a Windows executable-file. Can you please deliver it? Thanks a lot!

Regards, 
Nicolas

**Comment by ColinPitrat** [comment]
Hello,

here is the link to the exe:
https://drive.google.com/file/d/0BweL-sTrQlo_dXBqeXlCR2RIaUE/view?usp=sharing

Regards,
Colin

**Comment by Eindhoven562** [comment]
Hello Colin,

I'm sorry to inform you that the error is still there. This fix is not a solution. After starting guiding additional lines still appear at the screen.

You mentioned that there are additional points added when using the Kalenji-reader. Can that cause the problem? I did find out that guiding is working correctly when I reduce the number of points significantly. I just repeated that test. If I use a GPX-file that contains 100 points guiding works correct. If I use a GPS-file that contains 199 files, than the error occurs (and the additional lines appear).

Can there by some kind of overflow or something? It seems to be that the maximum capacity of the watch is limited at 199 points. Can the adding of additional (intermediate) points cause this limit to be exceeded?

Regards,
Nicolas

**Comment by ColinPitrat** [comment]
Hello,

if it works with less point, then maybe the limit is lower than 200 points ?
Did you try with intermediate values (150 points typically, then 125 if it doesn't work, 175 otherwise etc ...) ?

It would be interesting to see what a big file uploaded with Geonaute-uploader gives. In your example, the file produced has only 63 points instead of the 199 contained in the gpx. Maybe because 199 is too much and the uploader had to apply a logic to reduce it ? If this is the case, it means you need to use ReducePoints with reduce_points_max set to a value lower than 200.

Regards,
Colin

**Comment by Eindhoven562** [comment]
Hello,

That's interesting! I knew that Geonaute-uploader reduces the number of points, but I thought that it only did so with files containing more than approximately 199 points. I have used the Geonaute-uploader for a big file (1646 points) en it produces a GHR-files that works fine. I will upload both files (renamed to .jpg). Can you please check out how many points this GHR-file contains? That is probably the limit.

I have tried Kalenji-reader some time ago with a lot of files, but I don't remember the exact details any more. As far as I can remember 200, 199, 180, 160 and 150 was too high. 100 was working fine. I will do some more testing to see what the actual limit is.

With regards,
Nicolas
![1646pointsgpx](https://cloud.githubusercontent.com/assets/11527891/9568429/05486e06-4f49-11e5-9d32-afd71661632f.jpg)
![f8ui3949 ghr](https://cloud.githubusercontent.com/assets/11527891/9568430/054b0b5c-4f49-11e5-9336-23ea1503acae.jpg)

**Comment by ColinPitrat** [comment]
Hello,

the GHR file contains only 75 points ! For a session of 21.8km it's about a point every 300m in average.
Was the guiding precise ? If yes, it interests me much because from my experience, even with 200 points it's hard to obtain a precise guiding with ReducePoints filter. Maybe having a closer look at this example will give me idea to improve the precision.

I don't know how Geonaute-uploader behaves but for ReducePoints, the algorithm is executing multiple passes eliminating more points each time until it reaches a number of points below the maximum. It means that even if the maximum is 200 points and you have more than that, you can end-up with a bit less than 200 because the last pass removed more points than what was strictly needed. If Geonaute-uploader behaves the same way, maybe the max is 100 but the session was reduced of 25 extra points.

Regards,
Colin

**Comment by ColinPitrat** [comment]
I extracted the map corresponding to the two files you sent me. I'll have a closer look but it seems like a good candidate for reducing points massively because there are a lot of straight lines. So despite the low number of points, the guiding can still be precise.
We can clearly see the difference between the two paths and yet the guiding is still very precise.

75 points:
https://drive.google.com/file/d/0BweL-sTrQlo_dUdHQXdVMUdGSms/view?usp=sharing

1.6k points:
https://drive.google.com/file/d/0BweL-sTrQlo_ckZYaDl3N0JYcE0/view?usp=sharing

**Comment by ColinPitrat** [comment]
Hello,

do you confirm everything works well with a limit to 100 points ?
Do you see a significant difference in the quality of the guiding between kalenji_reader and Geonaute-uploader ?

Regards,
Colin

**Comment by Eindhoven562** [comment]
Hello Colin,

Nice to hear from you again!

I have done some testing with a various number of points. It turns out that 119 points is the maximum for reliable guiding with the watch. Problems occure when using more than 119 points (then additional lines appear at the screen).

Guiding with 119 points is pretty good (seems to be as good as the Geonaute-uploader). However, I cannot judge the performance of the kalenji-reader-algorithm (Reducepoints), because I use gpsbabel to reduce the number of point.

With regards,
Nicolas

**Comment by ColinPitrat** [comment]
Perfect, I'll close this issue then.
Don't hesitate to open another one if you encounter some issues.
